### ISSUE TITLE
attempt to index a nil value. 

### ISSUE THREAD

**Issue by Beta-Bella** [MenanAk47/ak47_clothing#1]
Hello dear Menan! 

First of all i love your clohingmenu script. We bought it in onetime and we are absolut in love with it. 
I tried to reach out to you on your discord but i cant write anywhere in there so i will try to explain my problem here. 

I personally have no problem with accessing your clothingmenu - it works perfectly with me  and my Serverstaff members. But all my players cannot access it - I already reinstalled it completly new but we still get the error shown on the picture i added to this thread. 

We run on the latest ESX Legacy, use Ox-inventory and a few of its modules. And since the 3rd of July we get this specific error - and i dont know why. I havent changed anything prior to before where it was working perfectly fine. 

If you have any questions let me know. 
lovely greetings bella.

![image_2023-07-05_231922917](https://github.com/MenanAk47/ak47_clothing/assets/128776783/403f001e-e286-44e2-b905-bf041f2620b0)

**Comment by MenanAk47** [comment]
Try to install the sql that comes with the script. Also make sure you have
property in database->datastore

**Comment by Beta-Bella** [comment]
So i ran the sql again - And the property thing is there too - but still the players cant access the shop. 
![image](https://github.com/MenanAk47/ak47_clothing/assets/128776783/9a1f2449-7539-4b8f-9247-73825a23a502)
I added a picture for you again.
